### PR TITLE
Added readme

### PR DESCRIPTION
**Pull request by craigsapp**
Added instructions for compiling in README.md and added repository property in package.json to suppress warning (in newer versions of node).

### CODE REVIEW

**Comment by craigsapp** [comment]
Added instructions for compiling in README.md and added repository property in package.json to suppress warning (in newer versions of node).

**Comment by raffazizzi** [comment]
Any reason why this was closed? If not, I'm happy to merge it (and thanks!)

**Comment by craigsapp** [comment]
Hi Raff,

I thought I was supposed to close to have it processed.   I'll open it up
now.

-=+Craig

**Comment by craigsapp** [comment]
Try #2: Added instructions for compiling in README.md and added repository property in package.json to suppress warning (in newer versions of node).

**Pull request merged**
